spring.datasource.url=jdbc:postgresql://localhost:5432/actmoneytransfer
spring.datasource.username=actmonertransferadmin
spring.datasource.password=postgres@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
